### ISSUE TITLE
`Sqs.to_*_batch()` methods missing from CDK v2 supported packages

### ISSUE THREAD

**Issue by brad-lucas** [udondan/iam-floyd#101]
**I'm using the package**

- [ ] iam-floyd
- [x] cdk-iam-floyd

**I'm using the package in language**
- [ ] TypeScript/JavaScript (npm)
- [x] Python (pip)

**Describe the problem**
Since upgrading to a version supporting CDK v2 (currently using latest - `0.304.0`), I no longer have access to methods supporting batch operations in SQS.

```python
import cdk_iam_floyd as statement

...

statement.Sqs()
    .allow()
    .to_send_message()
    .to_send_message_batch()              # no longer exists
    .to_delete_message()
    .to_delete_message_batch()            # no longer exists
    .to_change_message_visibility()
    .to_change_message_visibility_batch() # no longer exists
```

**Comment by brad-lucas** [comment]
Looking at the SQS CDK docs, batch support might be intentionally moved within the non-batch operations. Will report back.

**Comment by udondan** [comment]
Hi Brad,

looking at the history of the Floyd code, I cannot find any of the batch methods in previous versions of the library. What exact version were you using before for CDK 1? 

If those are valid permissions, they are undocumented. The Floyd code is generated fully automated by parsing the [AWS IAM documentation](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonsqs.html). If you think those permissions are valid, you need to [report it to AWS](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=Service%20Authorization%20Docs&topic_url=http://docs.aws.amazon.com/en_us/service-authorization/latest/reference/list_amazonsqs.html) to get it added to the AWS docs.

For undocumented actions you can always just use [`.to("whatever")`](https://iam-floyd.readthedocs.io/en/v0.305.0/vocabulary.html#to-action)

Cheers,
Daniel

**Comment by brad-lucas** [comment]
Thanks for the feedback, Daniel.

I still haven't been able to fully validate that the SQS `*Batch` permissions were lumped under their non-batch counterparts: our CDK v2 migration is in PR and just looking to finalize things next week without the `.to_*_batch()` methods.

As a reference point that was working (i.e. outputting the expected permissions from `cdk` CLI commands), we were pinned to `"cdk-iam-floyd" = "==0.209.0"`.

**Comment by udondan** [comment]
Found it. Those *batch permissions have been removed from the AWS docs on September 18 '21. They are gone since Floyd [v0.245.0](https://github.com/udondan/iam-floyd/releases/tag/v0.245.0).

[This SO question](https://stackoverflow.com/q/70088748/2753241) suggests the non-batch-permissions will not allow the batch actions though. If that's the case, then unfortunately you will have to work with the `to` method and pass the permissions as string.

I'll close this issue, because there's nothing I can do about it. Even though I know the docs are not always correct, I have to trust them or it would be a nightmare to maintain this project. 😸
