### ISSUE TITLE
Cannot create a statement with both resources and principals

### ISSUE THREAD

**Issue by gshpychka** [udondan/iam-floyd#120]
**I'm using the package**

- [ ] iam-floyd
- [x] cdk-iam-floyd

**I'm using the package in language**
- [ ] TypeScript/JavaScript (npm)
- [x] Python (pip)

**Describe the problem**

Creating a statement that contains resources and a principal does not work.

```
endpoint_policy_statement = (
    statement.Secretsmanager()
    .to_get_secret_value()
    .on_secret(
        account=self.account,
        region=self.region,
        secret_id=credentials.secret_name,
    )
    .for_cdk_principal(
       iam.AnyPrincipal()
    )
)

# this fails
assert endpoint_policy_statement.has_principals()
```

**Comment by gshpychka** [comment]
@udondan can you reproduce this?

**Comment by udondan** [comment]
Thanks for the ticket @gshpychka and bringing this to my attention.

The `.hasXxx()` methods currently don't work. That's because all actions/resources/principals/conditions are only stored internally and will be applied to the statement, when it is rendered - that is, when the `.toJSON()` method is called, which CDK does when it's writing the CFN template.

I will need to override those hasXxx methods and additionally check the internal store.

In the meantime you could just call `.toJSON()` (not sure what it's called in Python, might be `to_json`) before the assertion.

**Comment by udondan** [comment]
Oh wait, actually I already have those methods. 😕 Got to check.

**Comment by gshpychka** [comment]
The issue is when I pass this statement to a CDK construct that requires resources and principals, it complains that the statement doesn't have principals.

**Comment by udondan** [comment]
sorry, i currently do not possess the time to look into this. failing to set up a working python env to deploy a CDK stack.

**Comment by gshpychka** [comment]
> sorry, i currently do not possess the time to look into this. failing to set up a working python env to deploy a CDK stack.

That should be easy, can I help? All you need is create a virtualenv and create a single python file with a rudimentary app that deploys a single stack.

**Comment by gshpychka** [comment]
Hi @udondan, any progress on this? Can I help with the environment?

**Comment by gshpychka** [comment]
Hi @udondan, can I help with this somehow?

**Comment by gshpychka** [comment]
@udondan any updates?

**Comment by udondan** [comment]
Closing this as I have dropped jsii and with that Python support completely. The project was completely stuck for a year because of jsii problems and i decided to rather build a good TypeScript project than to deal with jsii issues over and over again.
